"""Auto-generated task registry. Regenerate: python3 build_registry.py"""

TASKS = [
    {
        "id": 'M1-AUT-REQ',
        "folder": 'm01-sdd',
        "title": 'Authentication — Requirements',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/authentication/requirements.md` aligned with SRS FR-AUTH-* and architecture docs.',
        "deps": ['M0'],
        "traces": '`features/authentication/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/authentication/requirements.md', 'features/authentication/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-AUT-ARC',
        "folder": 'm01-sdd',
        "title": 'Authentication — Architecture Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/authentication/architecture.md` aligned with SRS FR-AUTH-* and architecture docs.',
        "deps": ['M1-AUT-REQ'],
        "traces": '`features/authentication/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/authentication/architecture.md', 'features/authentication/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-AUT-DAT',
        "folder": 'm01-sdd',
        "title": 'Authentication — Data Model',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/authentication/data_model.md` aligned with SRS FR-AUTH-* and architecture docs.',
        "deps": ['M1-AUT-ARC'],
        "traces": '`features/authentication/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/authentication/data_model.md', 'features/authentication/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-AUT-API',
        "folder": 'm01-sdd',
        "title": 'Authentication — API Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/authentication/api_design.md` aligned with SRS FR-AUTH-* and architecture docs.',
        "deps": ['M1-AUT-DAT'],
        "traces": '`features/authentication/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/authentication/api_design.md', 'features/authentication/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-AUT-TST',
        "folder": 'm01-sdd',
        "title": 'Authentication — Tests + Implementation Tasks',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Write `tests.md` and `implementation_tasks.md` for authentication.',
        "deps": ['M1-AUT-API'],
        "traces": '`features/authentication/acceptance_criteria.md`',
        "acceptance": ['Each P0 AC has ≥1 test case', 'implementation_tasks.md chunks are ≤4h each', 'Written approval to implement recorded'],
        "files": ['features/authentication/tests.md', 'features/authentication/implementation_tasks.md'],
        "tests": 'QA Lead review',
    },
    {
        "id": 'M1-SEA-REQ',
        "folder": 'm01-sdd',
        "title": 'Property Search — Requirements',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/property_search/requirements.md` aligned with SRS FR-SEARCH-* and architecture docs.',
        "deps": ['M0'],
        "traces": '`features/property_search/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/property_search/requirements.md', 'features/property_search/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-SEA-ARC',
        "folder": 'm01-sdd',
        "title": 'Property Search — Architecture Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/property_search/architecture.md` aligned with SRS FR-SEARCH-* and architecture docs.',
        "deps": ['M1-SEA-REQ'],
        "traces": '`features/property_search/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/property_search/architecture.md', 'features/property_search/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-SEA-DAT',
        "folder": 'm01-sdd',
        "title": 'Property Search — Data Model',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/property_search/data_model.md` aligned with SRS FR-SEARCH-* and architecture docs.',
        "deps": ['M1-SEA-ARC'],
        "traces": '`features/property_search/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/property_search/data_model.md', 'features/property_search/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-SEA-API',
        "folder": 'm01-sdd',
        "title": 'Property Search — API Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/property_search/api_design.md` aligned with SRS FR-SEARCH-* and architecture docs.',
        "deps": ['M1-SEA-DAT'],
        "traces": '`features/property_search/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/property_search/api_design.md', 'features/property_search/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-SEA-TST',
        "folder": 'm01-sdd',
        "title": 'Property Search — Tests + Implementation Tasks',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Write `tests.md` and `implementation_tasks.md` for property_search.',
        "deps": ['M1-SEA-API'],
        "traces": '`features/property_search/acceptance_criteria.md`',
        "acceptance": ['Each P0 AC has ≥1 test case', 'implementation_tasks.md chunks are ≤4h each', 'Written approval to implement recorded'],
        "files": ['features/property_search/tests.md', 'features/property_search/implementation_tasks.md'],
        "tests": 'QA Lead review',
    },
    {
        "id": 'M1-PRO-REQ',
        "folder": 'm01-sdd',
        "title": 'Profile — Requirements',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/profile/requirements.md` aligned with SRS FR-PROF-* and architecture docs.',
        "deps": ['M0'],
        "traces": '`features/profile/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/profile/requirements.md', 'features/profile/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-PRO-ARC',
        "folder": 'm01-sdd',
        "title": 'Profile — Architecture Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/profile/architecture.md` aligned with SRS FR-PROF-* and architecture docs.',
        "deps": ['M1-PRO-REQ'],
        "traces": '`features/profile/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/profile/architecture.md', 'features/profile/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-PRO-DAT',
        "folder": 'm01-sdd',
        "title": 'Profile — Data Model',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/profile/data_model.md` aligned with SRS FR-PROF-* and architecture docs.',
        "deps": ['M1-PRO-ARC'],
        "traces": '`features/profile/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/profile/data_model.md', 'features/profile/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-PRO-API',
        "folder": 'm01-sdd',
        "title": 'Profile — API Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/profile/api_design.md` aligned with SRS FR-PROF-* and architecture docs.',
        "deps": ['M1-PRO-DAT'],
        "traces": '`features/profile/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/profile/api_design.md', 'features/profile/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-PRO-TST',
        "folder": 'm01-sdd',
        "title": 'Profile — Tests + Implementation Tasks',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Write `tests.md` and `implementation_tasks.md` for profile.',
        "deps": ['M1-PRO-API'],
        "traces": '`features/profile/acceptance_criteria.md`',
        "acceptance": ['Each P0 AC has ≥1 test case', 'implementation_tasks.md chunks are ≤4h each', 'Written approval to implement recorded'],
        "files": ['features/profile/tests.md', 'features/profile/implementation_tasks.md'],
        "tests": 'QA Lead review',
    },
    {
        "id": 'M1-CHT-REQ',
        "folder": 'm01-sdd',
        "title": 'Ai Chat — Requirements',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/ai_chat/requirements.md` aligned with SRS FR-CHAT-* and architecture docs.',
        "deps": ['M0'],
        "traces": '`features/ai_chat/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/ai_chat/requirements.md', 'features/ai_chat/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-CHT-ARC',
        "folder": 'm01-sdd',
        "title": 'Ai Chat — Architecture Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/ai_chat/architecture.md` aligned with SRS FR-CHAT-* and architecture docs.',
        "deps": ['M1-CHT-REQ'],
        "traces": '`features/ai_chat/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/ai_chat/architecture.md', 'features/ai_chat/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-CHT-DAT',
        "folder": 'm01-sdd',
        "title": 'Ai Chat — Data Model',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/ai_chat/data_model.md` aligned with SRS FR-CHAT-* and architecture docs.',
        "deps": ['M1-CHT-ARC'],
        "traces": '`features/ai_chat/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/ai_chat/data_model.md', 'features/ai_chat/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-CHT-API',
        "folder": 'm01-sdd',
        "title": 'Ai Chat — API Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/ai_chat/api_design.md` aligned with SRS FR-CHAT-* and architecture docs.',
        "deps": ['M1-CHT-DAT'],
        "traces": '`features/ai_chat/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/ai_chat/api_design.md', 'features/ai_chat/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-CHT-TST',
        "folder": 'm01-sdd',
        "title": 'Ai Chat — Tests + Implementation Tasks',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Write `tests.md` and `implementation_tasks.md` for ai_chat.',
        "deps": ['M1-CHT-API'],
        "traces": '`features/ai_chat/acceptance_criteria.md`',
        "acceptance": ['Each P0 AC has ≥1 test case', 'implementation_tasks.md chunks are ≤4h each', 'Written approval to implement recorded'],
        "files": ['features/ai_chat/tests.md', 'features/ai_chat/implementation_tasks.md'],
        "tests": 'QA Lead review',
    },
    {
        "id": 'M1-REC-REQ',
        "folder": 'm01-sdd',
        "title": 'Recommendation — Requirements',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/recommendation/requirements.md` aligned with SRS FR-REC-* and architecture docs.',
        "deps": ['M0'],
        "traces": '`features/recommendation/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/recommendation/requirements.md', 'features/recommendation/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-REC-ARC',
        "folder": 'm01-sdd',
        "title": 'Recommendation — Architecture Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/recommendation/architecture.md` aligned with SRS FR-REC-* and architecture docs.',
        "deps": ['M1-REC-REQ'],
        "traces": '`features/recommendation/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/recommendation/architecture.md', 'features/recommendation/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-REC-DAT',
        "folder": 'm01-sdd',
        "title": 'Recommendation — Data Model',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/recommendation/data_model.md` aligned with SRS FR-REC-* and architecture docs.',
        "deps": ['M1-REC-ARC'],
        "traces": '`features/recommendation/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/recommendation/data_model.md', 'features/recommendation/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-REC-API',
        "folder": 'm01-sdd',
        "title": 'Recommendation — API Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/recommendation/api_design.md` aligned with SRS FR-REC-* and architecture docs.',
        "deps": ['M1-REC-DAT'],
        "traces": '`features/recommendation/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/recommendation/api_design.md', 'features/recommendation/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-REC-TST',
        "folder": 'm01-sdd',
        "title": 'Recommendation — Tests + Implementation Tasks',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Write `tests.md` and `implementation_tasks.md` for recommendation.',
        "deps": ['M1-REC-API'],
        "traces": '`features/recommendation/acceptance_criteria.md`',
        "acceptance": ['Each P0 AC has ≥1 test case', 'implementation_tasks.md chunks are ≤4h each', 'Written approval to implement recorded'],
        "files": ['features/recommendation/tests.md', 'features/recommendation/implementation_tasks.md'],
        "tests": 'QA Lead review',
    },
    {
        "id": 'M1-BOK-REQ',
        "folder": 'm01-sdd',
        "title": 'Booking — Requirements',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/booking/requirements.md` aligned with SRS FR-BOOK-* and architecture docs.',
        "deps": ['M0'],
        "traces": '`features/booking/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/booking/requirements.md', 'features/booking/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-BOK-ARC',
        "folder": 'm01-sdd',
        "title": 'Booking — Architecture Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/booking/architecture.md` aligned with SRS FR-BOOK-* and architecture docs.',
        "deps": ['M1-BOK-REQ'],
        "traces": '`features/booking/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/booking/architecture.md', 'features/booking/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-BOK-DAT',
        "folder": 'm01-sdd',
        "title": 'Booking — Data Model',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/booking/data_model.md` aligned with SRS FR-BOOK-* and architecture docs.',
        "deps": ['M1-BOK-ARC'],
        "traces": '`features/booking/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/booking/data_model.md', 'features/booking/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-BOK-API',
        "folder": 'm01-sdd',
        "title": 'Booking — API Design',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Author `features/booking/api_design.md` aligned with SRS FR-BOOK-* and architecture docs.',
        "deps": ['M1-BOK-DAT'],
        "traces": '`features/booking/user_stories.md`, `specs/requirements.md`',
        "acceptance": ['Artifact complete; PO + Tech Lead sign-off', 'All P0 stories traced to FR IDs', 'No TBDs blocking implementation_tasks.md'],
        "files": ['features/booking/api_design.md', 'features/booking/README.md'],
        "tests": 'Peer review checklist in feature README',
    },
    {
        "id": 'M1-BOK-TST',
        "folder": 'm01-sdd',
        "title": 'Booking — Tests + Implementation Tasks',
        "milestone": 'M1 — SDD Completion',
        "estimate": '2–3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'spec',
        "description": 'Write `tests.md` and `implementation_tasks.md` for booking.',
        "deps": ['M1-BOK-API'],
        "traces": '`features/booking/acceptance_criteria.md`',
        "acceptance": ['Each P0 AC has ≥1 test case', 'implementation_tasks.md chunks are ≤4h each', 'Written approval to implement recorded'],
        "files": ['features/booking/tests.md', 'features/booking/implementation_tasks.md'],
        "tests": 'QA Lead review',
    },
    {
        "id": 'M2-PLT001',
        "folder": 'm02-platform',
        "title": 'Flutter Platform Bootstrap',
        "milestone": 'M2 — Platform Bootstrap',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'done',
        "layer": 'mobile',
        "description": 'Initialize Flutter app with flavors, Riverpod, GoRouter, Dio, Freezed, Injectable, CI.',
        "deps": ['M1-AUT-TST'],
        "traces": '`architecture/flutter_architecture.md`',
        "acceptance": ['`flutter analyze` passes', '`flutter test` passes', '`flutter run --flavor dev` works on iOS/Android'],
        "files": ['mobile/lib/**', 'mobile/pubspec.yaml', '.github/workflows/mobile-ci.yml'],
        "tests": '`flutter test`; see mobile_platform_bootstrap_completion_report.md',
    },
    {
        "id": 'M2-PLT002',
        "folder": 'm02-platform',
        "title": 'NestJS Scaffold + Clean Architecture Folders',
        "milestone": 'M2 — Platform Bootstrap',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'Create NestJS app with domain/application/infrastructure/presentation layers per PROJECT_STRUCTURE.',
        "deps": ['M1-AUT-TST'],
        "traces": '`backend/PROJECT_STRUCTURE.md`, `architecture/clean_architecture.md`',
        "acceptance": ['`npm run build` succeeds', 'Domain folder has zero NestJS imports', 'AppModule boots without feature logic'],
        "files": ['backend/src/main.ts', 'backend/src/app.module.ts', 'backend/src/domain/**', 'backend/package.json'],
        "tests": 'Unit: AppModule compiles; lint passes',
    },
    {
        "id": 'M2-PLT003',
        "folder": 'm02-platform',
        "title": 'Prisma Schema + Initial Migration',
        "milestone": 'M2 — Platform Bootstrap',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'Implement Prisma schema from postgresql_schema.md; enable pgvector extension.',
        "deps": ['M2-PLT002'],
        "traces": '`architecture/postgresql_schema.md`',
        "acceptance": ['`prisma migrate dev` applies on clean DB', 'vector extension enabled', 'Seed script stub runs'],
        "files": ['backend/prisma/schema.prisma', 'backend/prisma/migrations/**', 'backend/prisma/seed/**'],
        "tests": "Integration: migration + pg_extension extname='vector'",
    },
    {
        "id": 'M2-PLT004',
        "folder": 'm02-platform',
        "title": 'Docker Compose Local Stack',
        "milestone": 'M2 — Platform Bootstrap',
        "estimate": '2h',
        "priority": 'P0',
        "layer": 'infra',
        "description": 'Postgres (pgvector), Redis, API container for local dev.',
        "deps": ['M2-PLT003'],
        "traces": '`architecture/deployment_architecture.md` §12',
        "acceptance": ['`docker compose up` starts all services', 'Postgres reachable from API', 'Redis reachable from API'],
        "files": ['backend/docker-compose.yml', 'backend/Dockerfile', 'backend/.env.example'],
        "tests": 'Smoke: curl /health after compose up',
    },
    {
        "id": 'M2-PLT005',
        "folder": 'm02-platform',
        "title": 'Health Endpoints + Logging Interceptor',
        "milestone": 'M2 — Platform Bootstrap',
        "estimate": '2h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'GET /health and /health/ready; Pino JSON logs with correlation ID.',
        "deps": ['M2-PLT002'],
        "traces": 'NFR-OBS-001, `architecture/monitoring_strategy.md`',
        "acceptance": ['/health returns 200', '/health/ready fails when DB down', 'Logs include correlationId field'],
        "files": ['backend/src/presentation/health/**', 'backend/src/common/interceptors/logging.interceptor.ts'],
        "tests": 'Integration: supertest health; ready probe with stopped DB',
    },
    {
        "id": 'M2-PLT006',
        "folder": 'm02-platform',
        "title": 'Backend CI Pipeline Skeleton',
        "milestone": 'M2 — Platform Bootstrap',
        "estimate": '2h',
        "priority": 'P0',
        "layer": 'ci',
        "description": 'GitHub Actions: lint, test, docker build on PR.',
        "deps": ['M2-PLT002'],
        "traces": '`architecture/deployment_architecture.md` §6.2',
        "acceptance": ['backend-ci.yml runs on PR', 'Fails on lint errors', 'Builds Docker image (no push on PR)'],
        "files": ['.github/workflows/backend-ci.yml'],
        "tests": 'Push PR and verify CI green',
    },
    {
        "id": 'M2-PLT007',
        "folder": 'm02-platform',
        "title": 'Redis + BullMQ Module Wiring',
        "milestone": 'M2 — Platform Bootstrap',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'Register BullMQ root module and empty worker bootstrap.',
        "deps": ['M2-PLT004'],
        "traces": '`architecture/backend_architecture.md`',
        "acceptance": ['Redis connection from env', 'Sample queue job enqueues and processes', 'Worker entrypoint starts'],
        "files": ['backend/src/infrastructure/queue/**', 'backend/src/worker.ts'],
        "tests": 'Integration: enqueue ping job, assert completed',
    },
    {
        "id": 'M3-AUTH001',
        "folder": 'm03-authentication',
        "title": 'Auth Domain Layer (entities, ports, VOs)',
        "milestone": 'M3 — Authentication',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'User role enum, Email/Password VOs, auth repository port, token service port.',
        "deps": ['M2-PLT003', 'M1-AUT-REQ'],
        "traces": 'FR-AUTH-*, `features/authentication/data_model.md`',
        "acceptance": ['Domain unit tests ≥80% for auth domain', 'No framework imports in domain/', 'Password VO enforces min length 8'],
        "files": ['backend/src/domain/auth/**', 'backend/test/unit/domain/auth/**'],
        "tests": 'Unit: email validation, password rules, role enum',
    },
    {
        "id": 'M3-AUTH002',
        "folder": 'm03-authentication',
        "title": 'JWT + Refresh Token Service',
        "milestone": 'M3 — Authentication',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'Issue access (15m) and refresh tokens with rotation; Prisma refresh_tokens table.',
        "deps": ['M3-AUTH001'],
        "traces": 'FR-AUTH-006, AC-AUTH-004',
        "acceptance": ['Access token expires per config', 'Refresh rotation invalidates old token', 'Tampered token rejected'],
        "files": ['backend/src/infrastructure/auth/jwt-token.service.ts', 'backend/src/infrastructure/persistence/auth/**'],
        "tests": 'Unit: sign/verify; Integration: refresh flow',
    },
    {
        "id": 'M3-AUTH003',
        "folder": 'm03-authentication',
        "title": 'POST /auth/register + Email Verification',
        "milestone": 'M3 — Authentication',
        "estimate": '4h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'Register endpoint, duplicate email check, verification email job.',
        "deps": ['M3-AUTH002'],
        "traces": 'FR-AUTH-001, FR-AUTH-009, AC-AUTH-001, AC-AUTH-007',
        "acceptance": ['Valid registration returns 201 + verification pending', 'Duplicate email returns 409', 'Unverified user blocked from protected routes'],
        "files": ['backend/src/modules/auth/**', 'backend/src/application/auth/register.use-case.ts'],
        "tests": 'Integration: register happy path + duplicate + unverified guard',
    },
    {
        "id": 'M3-AUTH004',
        "folder": 'm03-authentication',
        "title": 'POST /auth/login + Logout',
        "milestone": 'M3 — Authentication',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'Login with email/password; logout invalidates refresh token.',
        "deps": ['M3-AUTH003'],
        "traces": 'FR-AUTH-004, AC-AUTH-004, AC-AUTH-005',
        "acceptance": ['Correct credentials return token pair', 'Wrong password returns 401', 'Logout returns 204 and revokes refresh'],
        "files": ['backend/src/application/auth/login.use-case.ts', 'backend/src/application/auth/logout.use-case.ts'],
        "tests": 'Integration: login/logout; wrong password',
    },
    {
        "id": 'M3-AUTH005',
        "folder": 'm03-authentication',
        "title": 'Password Reset Flow',
        "milestone": 'M3 — Authentication',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'forgot-password and reset-password endpoints with email link.',
        "deps": ['M3-AUTH004'],
        "traces": 'FR-AUTH-005, AC-AUTH-006',
        "acceptance": ['Reset email sent for known email', 'Unknown email returns same response (no leak)', 'Reset token single-use'],
        "files": ['backend/src/application/auth/forgot-password.use-case.ts', 'backend/src/application/auth/reset-password.use-case.ts'],
        "tests": 'Integration: full reset flow with mock email',
    },
    {
        "id": 'M3-AUTH006',
        "folder": 'm03-authentication',
        "title": 'Google OAuth Backend',
        "milestone": 'M3 — Authentication',
        "estimate": '4h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'POST /auth/google with Passport; oauth_accounts linking.',
        "deps": ['M3-AUTH004'],
        "traces": 'FR-AUTH-002, AC-AUTH-002',
        "acceptance": ['Valid Google token creates/links user', 'Cancelled flow returns 400', 'New user prompted for role in response metadata'],
        "files": ['backend/src/infrastructure/auth/google.strategy.ts', 'backend/src/presentation/auth/auth.controller.ts'],
        "tests": 'Integration: mock Google token',
    },
    {
        "id": 'M3-AUTH007',
        "folder": 'm03-authentication',
        "title": 'Apple Sign-In Backend',
        "milestone": 'M3 — Authentication',
        "estimate": '4h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'POST /auth/apple; handle private relay emails.',
        "deps": ['M3-AUTH006'],
        "traces": 'FR-AUTH-003, AC-AUTH-003',
        "acceptance": ['Valid Apple identity token logs user in', 'Private relay email stored correctly'],
        "files": ['backend/src/infrastructure/auth/apple.strategy.ts'],
        "tests": 'Integration: mock Apple JWT',
    },
    {
        "id": 'M3-AUTH008',
        "folder": 'm03-authentication',
        "title": 'RBAC Guards + JWT Passport',
        "milestone": 'M3 — Authentication',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'backend',
        "description": 'JwtAuthGuard, RolesGuard, @Roles() decorator on protected routes.',
        "deps": ['M3-AUTH002'],
        "traces": 'FR-AUTH-013, AC-AUTH-013',
        "acceptance": ['Buyer cannot access agent-only endpoint (403)', 'Missing token returns 401', 'Valid token attaches user to request'],
        "files": ['backend/src/presentation/guards/**', 'backend/src/presentation/decorators/roles.decorator.ts'],
        "tests": 'Integration: protected route role matrix',
    },
    {
        "id": 'M3-AUTH009',
        "folder": 'm03-authentication',
        "title": 'Mobile Auth Screens (Register, Login, Onboarding)',
        "milestone": 'M3 — Authentication',
        "estimate": '4h',
        "priority": 'P0',
        "layer": 'mobile',
        "description": 'Replace placeholders with register/login/role selection; ar-EG + en.',
        "deps": ['M2-PLT001', 'M3-AUTH004'],
        "traces": 'AC-AUTH-001, AC-AUTH-009, AC-AUTH-010',
        "acceptance": ['User can register and see verification message', 'User can login and reach home', 'Role selection shown for new OAuth users'],
        "files": ['mobile/lib/features/authentication/**', 'mobile/lib/core/routing/route_guards.dart'],
        "tests": 'Widget tests for forms; manual E2E login',
    },
    {
        "id": 'M3-AUTH010',
        "folder": 'm03-authentication',
        "title": 'Mobile Google + Apple Sign-In',
        "milestone": 'M3 — Authentication',
        "estimate": '4h',
        "priority": 'P0',
        "layer": 'mobile',
        "description": 'Integrate google_sign_in and sign_in_with Apple; wire to API.',
        "deps": ['M3-AUTH009', 'M3-AUTH006', 'M3-AUTH007'],
        "traces": 'AC-AUTH-002, AC-AUTH-003',
        "acceptance": ['Google sign-in completes on Android/iOS', 'Apple sign-in works on iOS', 'Failed OAuth shows error, no orphan account'],
        "files": ['mobile/lib/features/authentication/data/datasources/**', 'mobile/pubspec.yaml'],
        "tests": 'Manual E2E on simulators; widget test error states',
    },
    {
        "id": 'M3-AUTH011',
        "folder": 'm03-authentication',
        "title": 'Mobile Token Storage + Auto Refresh',
        "milestone": 'M3 — Authentication',
        "estimate": '3h',
        "priority": 'P0',
        "layer": 'mobile',
        "description": 'Secure storage for tokens; Dio interceptor refresh on 401.',
        "deps": ['M3-AUTH009'],
        "traces": 'FR-AUTH-006, AC-AUTH-004',
        "acceptance": ['Tokens persist across app restart', 'Expired access refreshes transparently', 'Failed refresh redirects to login'],
        "files": ['mobile/lib/core/network/auth_interceptor.dart', 'mobile/lib/features/authentication/presentation/providers/**'],
        "tests": 'Unit: interceptor refresh mock; integration token persist',
    },
    {
        "id": 'M3-AUTH012',
        "folder": 'm03-authentication',
        "title": 'PDPL Consent on Onboarding',
        "milestone": 'M3 — Authentication',
        "estimate": '2h',
        "priority": 'P0',
        "layer": 'mobile',
        "description": 'Consent checkbox; store consent_at on user.',
        "deps": ['M3-AUTH009'],
        "traces": 'FR-AUTH-010, AC-AUTH-010',
        "acceptance": ['Cannot proceed without consent', 'consent_at sent to API on register'],
        "files": ['mobile/lib/features/authentication/presentation/pages/onboarding_page.dart', 'backend/src/application/auth/register.use-case.ts'],
        "tests": 'Widget: submit disabled without consent',
    },
    {
        "id": 'M4-SEA001',
        "folder": 'm04-property-search',
        "title": 'Listing Provider Port + Property Domain',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Define ListingProviderPort, Property entity, normalization rules.',
        "deps": ['M2-PLT003', 'M1-SEA-REQ'],
        "traces": 'FR-SEARCH-*, FR-SYNC-*, `features/property_search/data_model.md`',
        "acceptance": ['Domain ports have no NestJS imports', 'Property entity maps to Prisma schema', 'Unit tests for normalization edge cases'],
        "files": ['backend/src/domain/property/**', 'backend/test/unit/domain/property/**'],
        "tests": 'Unit: mapper tests with fixture JSON',
    },
    {
        "id": 'M4-SEA002',
        "folder": 'm04-property-search',
        "title": 'Shaety Listing Adapter (with mock fallback)',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'HTTP client for Shaety API; mock adapter when credentials absent.',
        "deps": ['M4-SEA001'],
        "traces": '`architecture/listing_providers.md`, FR-SYNC-001',
        "acceptance": ['Adapter implements ListingProviderPort', 'Mock returns ≥10 listings for local dev', 'Rate limit and retry on 429/5xx'],
        "files": ['backend/src/infrastructure/listing/shaety/**'],
        "tests": 'Integration: mock adapter ingest sample',
    },
    {
        "id": 'M4-SEA003',
        "folder": 'm04-property-search',
        "title": 'Properties Prisma Repository',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Upsert listings by external_id; soft-delete inactive after 24h.',
        "deps": ['M4-SEA001'],
        "traces": '`architecture/postgresql_schema.md` properties table',
        "acceptance": ['Upsert idempotent on external_id', 'Inactive listings excluded from search', 'Integration test with test DB'],
        "files": ['backend/src/infrastructure/persistence/property/**'],
        "tests": 'Integration: upsert + query active only',
    },
    {
        "id": 'M4-SEA004',
        "folder": 'm04-property-search',
        "title": 'Listing Sync BullMQ Worker',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Scheduled listing-sync job; sync_run audit rows; failure counter.',
        "deps": ['M4-SEA002', 'M4-SEA003', 'M2-PLT007'],
        "traces": 'FR-SYNC-002, FR-SYNC-004',
        "acceptance": ['Worker processes sync queue job', 'sync_runs row created per run', '3 failures increment alert metric'],
        "files": ['backend/src/infrastructure/queue/listing-sync.processor.ts', 'backend/src/worker.ts'],
        "tests": 'Integration: trigger job, assert property count',
    },
    {
        "id": 'M4-SEA005',
        "folder": 'm04-property-search',
        "title": 'Full-Text Search (tsvector) + Query Builder',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'GIN index on search_vector; bilingual query support.',
        "deps": ['M4-SEA003'],
        "traces": 'FR-SEARCH-003, architecture (pgvector + tsvector)',
        "acceptance": ['Arabic and English queries return results', 'tsvector updated on upsert', 'Explain plan acceptable on 10k rows (local)'],
        "files": ['backend/src/infrastructure/search/**'],
        "tests": "Integration: search 'Maadi' and 'المعادي'",
    },
    {
        "id": 'M4-SEA006',
        "folder": 'm04-property-search',
        "title": 'GET /api/v1/properties (filter, sort, paginate)',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Public search endpoint with city, price, beds, type filters.',
        "deps": ['M4-SEA005'],
        "traces": 'FR-SEARCH-001–011, `features/property_search/api_design.md`',
        "acceptance": ['Pagination metadata correct', 'Invalid filter returns 400', 'Guest access allowed (P1 browse)'],
        "files": ['backend/src/modules/properties/**', 'backend/src/application/property/search.use-case.ts'],
        "tests": 'Integration: filter matrix + pagination',
    },
    {
        "id": 'M4-SEA007',
        "folder": 'm04-property-search',
        "title": 'GET /api/v1/properties/:id',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Detail endpoint with provider attribution and image URLs.',
        "deps": ['M4-SEA003'],
        "traces": 'FR-SEARCH-012, FR-SEARCH-014',
        "acceptance": ['404 for unknown/inactive id', 'provider_name and source_url in response', 'OpenAPI/contract matches api_design.md'],
        "files": ['backend/src/presentation/properties/properties.controller.ts'],
        "tests": 'Integration: detail happy path + 404',
    },
    {
        "id": 'M4-SEA008',
        "folder": 'm04-property-search',
        "title": 'Admin Sync Status Endpoint',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'GET /admin/sync/status for last run, counts, errors (agent/admin).',
        "deps": ['M4-SEA004', 'M3-AUTH008'],
        "traces": 'FR-SYNC-006',
        "acceptance": ['Returns last sync timestamp and row counts', '403 for non-admin/agent roles'],
        "files": ['backend/src/presentation/admin/sync.controller.ts'],
        "tests": 'Integration: RBAC + response shape',
    },
    {
        "id": 'M4-SEA009',
        "folder": 'm04-property-search',
        "title": 'Mobile Search Screen + Results List',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Search bar, results ListView, empty/error states, ar-EG + en.',
        "deps": ['M2-PLT001', 'M4-SEA006'],
        "traces": 'AC-SEARCH-001, AC-SEARCH-002',
        "acceptance": ['Guest can browse results', 'Pull-to-refresh triggers reload', 'Widget tests for empty/error'],
        "files": ['mobile/lib/features/property_search/**'],
        "tests": 'Widget tests; manual guest browse',
    },
    {
        "id": 'M4-SEA010',
        "folder": 'm04-property-search',
        "title": 'Mobile Filters Bottom Sheet',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Price range, beds, property type, city filters applied to API.',
        "deps": ['M4-SEA009'],
        "traces": 'FR-SEARCH-004, AC-SEARCH-003',
        "acceptance": ['Applied filters reflected in query params', 'Clear filters resets list'],
        "files": ['mobile/lib/features/property_search/presentation/widgets/**'],
        "tests": 'Widget: filter apply/clear',
    },
    {
        "id": 'M4-SEA011',
        "folder": 'm04-property-search',
        "title": 'Mobile Listing Detail Screen',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Image carousel, attributes, provider badge, share stub.',
        "deps": ['M4-SEA009', 'M4-SEA007'],
        "traces": 'FR-SEARCH-012, AC-SEARCH-004',
        "acceptance": ['Opens from search result tap', 'Image error placeholder shown', 'Provider attribution visible'],
        "files": ['mobile/lib/features/property_search/presentation/pages/detail/**'],
        "tests": 'Widget + manual navigation from list',
    },
    {
        "id": 'M4-SEA012',
        "folder": 'm04-property-search',
        "title": 'Property Search Integration Test Pack',
        "milestone": 'M4 — Property Search & Listing Sync',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Supertest pack for sync + search + detail per tests.md P0 AC.',
        "deps": ['M4-SEA006', 'M4-SEA007', 'M4-SEA004'],
        "traces": '`features/property_search/tests.md`',
        "acceptance": ['All P0 API AC covered', 'CI runs search integration suite'],
        "files": ['backend/test/integration/properties/**'],
        "tests": '`npm run test:integration` green',
    },
    {
        "id": 'M5-PRO001',
        "folder": 'm05-profile',
        "title": 'Profile Domain + Repository Port',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'UserProfile entity, favorites port, preferences VOs.',
        "deps": ['M3-AUTH001', 'M1-PRO-REQ'],
        "traces": 'FR-PROF-*, `features/profile/data_model.md`',
        "acceptance": ['Domain tests ≥80% for profile module', 'No NestJS in domain/'],
        "files": ['backend/src/domain/profile/**', 'backend/test/unit/domain/profile/**'],
        "tests": 'Unit: preference validation',
    },
    {
        "id": 'M5-PRO002',
        "folder": 'm05-profile',
        "title": 'GET/PATCH /api/v1/users/me',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Profile read/update with locale, name, phone validation.',
        "deps": ['M5-PRO001', 'M3-AUTH008'],
        "traces": 'FR-PROF-001, FR-PROF-002',
        "acceptance": ['PATCH partial update works', '401 without token'],
        "files": ['backend/src/modules/users/**', 'backend/src/application/profile/update-profile.use-case.ts'],
        "tests": 'Integration: me read/update',
    },
    {
        "id": 'M5-PRO003',
        "folder": 'm05-profile',
        "title": 'Favorites CRUD API',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'POST/DELETE/GET favorites linked to property_id.',
        "deps": ['M5-PRO001', 'M4-SEA003'],
        "traces": 'FR-PROF-003, FR-PROF-004',
        "acceptance": ['Idempotent add favorite', '404 if property missing'],
        "files": ['backend/src/application/profile/favorites/**'],
        "tests": 'Integration: add/list/remove',
    },
    {
        "id": 'M5-PRO004',
        "folder": 'm05-profile',
        "title": 'Search Preferences API',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Persist budget, areas, property types on user preferences JSON.',
        "deps": ['M5-PRO002'],
        "traces": 'FR-PROF-005',
        "acceptance": ['Preferences round-trip in GET /me', 'Invalid budget returns 400'],
        "files": ['backend/src/application/profile/preferences/**'],
        "tests": 'Integration: update prefs reflected in GET /me',
    },
    {
        "id": 'M5-PRO005',
        "folder": 'm05-profile',
        "title": 'Default AI Agent Preference',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'PATCH default_agent_id; validate against ai_agents seed.',
        "deps": ['M5-PRO002'],
        "traces": 'FR-PROF-007',
        "acceptance": ['Invalid agent id returns 400', 'Default used by chat module (stub ok)'],
        "files": ['backend/src/application/profile/set-default-agent.use-case.ts'],
        "tests": 'Integration: set + get default agent',
    },
    {
        "id": 'M5-PRO006',
        "folder": 'm05-profile',
        "title": 'Account Deletion + Data Export Stub',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'DELETE /me with cascade; export job stub for PDPL.',
        "deps": ['M5-PRO002'],
        "traces": 'FR-PROF-009, FR-PROF-010',
        "acceptance": ['Deletion returns 204', 'PII removed per policy window documented'],
        "files": ['backend/src/application/profile/delete-account.use-case.ts'],
        "tests": 'Integration: delete then login fails',
    },
    {
        "id": 'M5-PRO007',
        "folder": 'm05-profile',
        "title": 'Agent Public Profile GET /agents/:id',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Public agent card: name, agency, languages, rating stub.',
        "deps": ['M5-PRO001'],
        "traces": 'FR-PROF-008',
        "acceptance": ['200 for agent role user', '404 for non-agent'],
        "files": ['backend/src/presentation/agents/agents.controller.ts'],
        "tests": 'Integration: agent profile',
    },
    {
        "id": 'M5-PRO008',
        "folder": 'm05-profile',
        "title": 'Mobile Profile Tab + Edit Profile',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Profile screen, edit form, locale switcher.',
        "deps": ['M3-AUTH009', 'M5-PRO002'],
        "traces": 'AC-PROF-001, AC-PROF-002',
        "acceptance": ['User updates name and sees change', 'ar-EG and en UI strings'],
        "files": ['mobile/lib/features/profile/**'],
        "tests": 'Widget tests; manual profile edit',
    },
    {
        "id": 'M5-PRO009',
        "folder": 'm05-profile',
        "title": 'Mobile Favorites Screen',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Favorites list with navigation to listing detail.',
        "deps": ['M5-PRO008', 'M5-PRO003', 'M4-SEA011'],
        "traces": 'FR-PROF-003',
        "acceptance": ['Add/remove favorite from detail', 'Favorites persist after restart'],
        "files": ['mobile/lib/features/profile/presentation/pages/favorites/**'],
        "tests": 'Widget + manual favorite flow',
    },
    {
        "id": 'M5-PRO010',
        "folder": 'm05-profile',
        "title": 'Profile P0 Integration Tests',
        "milestone": 'M5 — User Profile & Preferences',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Test pack for profile + favorites per tests.md.',
        "deps": ['M5-PRO003', 'M5-PRO006'],
        "traces": '`features/profile/tests.md`',
        "acceptance": ['All P0 profile AC pass in CI'],
        "files": ['backend/test/integration/profile/**'],
        "tests": '`npm run test:integration` profile suite green',
    },
    {
        "id": 'M6-RAG001',
        "folder": 'm06-rag',
        "title": 'Gemini Embedding Adapter',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Vertex/AI Studio embedding client with batching and retries.',
        "deps": ['M2-PLT007', 'M4-SEA003'],
        "traces": '`architecture/rag_architecture.md`, FR-SYNC-002',
        "acceptance": ['768-dim vectors returned', 'Retries on transient errors', 'Unit tests with mocked HTTP'],
        "files": ['backend/src/infrastructure/ai/embedding.service.ts'],
        "tests": 'Unit: mock embed response',
    },
    {
        "id": 'M6-RAG002',
        "folder": 'm06-rag',
        "title": 'embed-listing BullMQ Worker',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Queue job embeds new/updated listings into embeddings table.',
        "deps": ['M6-RAG001', 'M4-SEA004'],
        "traces": 'FR-SYNC-002, `architecture/postgresql_schema.md`',
        "acceptance": ['New listing gets embedding within worker run', 'Upsert on listing id'],
        "files": ['backend/src/infrastructure/queue/embed-listing.processor.ts'],
        "tests": 'Integration: listing → embedding row',
    },
    {
        "id": 'M6-RAG003',
        "folder": 'm06-rag',
        "title": 'HNSW Index Migration + pgvector Tuning',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Create HNSW index on embeddings; document ef_search settings.',
        "deps": ['M6-RAG002'],
        "traces": '`architecture/postgresql_schema.md`',
        "acceptance": ['Migration applies on staging DB', 'Similarity query uses index'],
        "files": ['backend/prisma/migrations/**'],
        "tests": 'SQL: EXPLAIN shows index usage',
    },
    {
        "id": 'M6-RAG004',
        "folder": 'm06-rag',
        "title": 'RAG Orchestrator (hybrid vector + SQL + tsvector)',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Retrieve top-k chunks with metadata filters (price, city).',
        "deps": ['M6-RAG003', 'M4-SEA005'],
        "traces": '`architecture/rag_architecture.md` §4',
        "acceptance": ['Hybrid query returns ranked results', 'Empty retrieval logged', 'p95 < 400ms on 1k listings (local)'],
        "files": ['backend/src/application/rag/rag-orchestrator.ts'],
        "tests": 'Integration: golden query set sample',
    },
    {
        "id": 'M6-RAG005',
        "folder": 'm06-rag',
        "title": 'POST /api/v1/ai/rag/retrieve (dev/admin)',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Debug retrieve endpoint returning chunks + listing IDs.',
        "deps": ['M6-RAG004', 'M3-AUTH008'],
        "traces": 'M6 independently runnable verification',
        "acceptance": ['Returns cited listing IDs', '403 for unauthorized roles if restricted'],
        "files": ['backend/src/presentation/ai/rag.controller.ts'],
        "tests": 'curl retrieve smoke test',
    },
    {
        "id": 'M6-RAG006',
        "folder": 'm06-rag',
        "title": 'Redis RAG Result Cache',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Cache identical queries; TTL 15m; cache hit metric.',
        "deps": ['M6-RAG004', 'M2-PLT007'],
        "traces": '`architecture/rag_architecture.md` §6',
        "acceptance": ['Second identical query < 20ms', 'Cache invalidates on listing update'],
        "files": ['backend/src/infrastructure/cache/rag-cache.service.ts'],
        "tests": 'Integration: cache hit timing',
    },
    {
        "id": 'M6-RAG007',
        "folder": 'm06-rag',
        "title": 'Project Knowledge Ingest (FAQ chunks)',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Ingest project FAQ markdown into embeddable chunks.',
        "deps": ['M6-RAG001'],
        "traces": 'FR-CHAT-007 (knowledge grounding)',
        "acceptance": ['Chunks stored with source metadata', 'Retrieve includes project context'],
        "files": ['backend/src/infrastructure/knowledge/**'],
        "tests": 'Integration: ingest + retrieve FAQ',
    },
    {
        "id": 'M6-RAG008',
        "folder": 'm06-rag',
        "title": 'RAG Metrics Instrumentation',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Prometheus: retrieve duration, empty rate, embed lag.',
        "deps": ['M6-RAG004'],
        "traces": '`architecture/monitoring_strategy.md`',
        "acceptance": ['Metrics exposed on /metrics', 'Grafana panel JSON stub committed'],
        "files": ['backend/src/infrastructure/observability/metrics/**'],
        "tests": 'Integration: metric increments on retrieve',
    },
    {
        "id": 'M6-RAG009',
        "folder": 'm06-rag',
        "title": 'RAG Golden-Set Evaluation Script',
        "milestone": 'M6 — Embeddings, RAG & Knowledge',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'CLI/script measuring recall@5 on labeled queries.',
        "deps": ['M6-RAG005'],
        "traces": '`architecture/rag_architecture.md` §8',
        "acceptance": ['Recall@5 ≥ target on golden set', 'Report artifact in CI optional job'],
        "files": ['backend/scripts/rag-eval.ts'],
        "tests": 'Run script locally; document baseline',
    },
    {
        "id": 'M7-CHT001',
        "folder": 'm07-ai-chat',
        "title": 'Conversation Domain + Repositories',
        "milestone": 'M7 — AI Chat',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Conversation, Message entities; ports for persistence.',
        "deps": ['M2-PLT003', 'M1-CHT-REQ'],
        "traces": '`features/ai_chat/data_model.md`',
        "acceptance": ['Domain unit tests pass', 'Maps to conversations/messages tables'],
        "files": ['backend/src/domain/chat/**', 'backend/test/unit/domain/chat/**'],
        "tests": 'Unit: message role validation',
    },
    {
        "id": 'M7-CHT002',
        "folder": 'm07-ai-chat',
        "title": 'AiModule + Agents Catalog API',
        "milestone": 'M7 — AI Chat',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'GET /ai/agents from seed; disabled agent flag.',
        "deps": ['M7-CHT001'],
        "traces": 'FR-CHAT-009',
        "acceptance": ['Returns 4 seeded agents', 'Disabled agent excluded or flagged'],
        "files": ['backend/src/modules/ai/**'],
        "tests": 'Integration: agents list',
    },
    {
        "id": 'M7-CHT003',
        "folder": 'm07-ai-chat',
        "title": 'GeminiOrchestrator + Prompt Version Loader',
        "milestone": 'M7 — AI Chat',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Load active prompt_template_version; call Vertex generate.',
        "deps": ['M7-CHT002', 'M6-RAG004'],
        "traces": '`architecture/gemini_integration_layer.md`',
        "acceptance": ['Uses pinned prompt version id', 'Structured logging of model id'],
        "files": ['backend/src/infrastructure/ai/gemini-orchestrator.ts'],
        "tests": 'Integration: mock Vertex response',
    },
    {
        "id": 'M7-CHT004',
        "folder": 'm07-ai-chat',
        "title": 'SafetyPipeline + Fair Housing Rules',
        "milestone": 'M7 — AI Chat',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Pre-filter blocked topics; refuse without model call.',
        "deps": ['M7-CHT003'],
        "traces": 'FR-CHAT-014, AC fair housing',
        "acceptance": ['Discriminatory query returns refusal', 'No Gemini call on blocked input (metric)'],
        "files": ['backend/src/application/chat/safety-pipeline.ts'],
        "tests": 'Unit: blocked phrase matrix',
    },
    {
        "id": 'M7-CHT005',
        "folder": 'm07-ai-chat',
        "title": 'ToolExecutionLoop (semantic_search, etc.)',
        "milestone": 'M7 — AI Chat',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Execute tools from Gemini function calls; audit toolsCalled.',
        "deps": ['M7-CHT003', 'M6-RAG004'],
        "traces": 'FR-CHAT-008, gemini integration §5',
        "acceptance": ['semantic_search returns listings', 'Tool errors surfaced to user safely'],
        "files": ['backend/src/application/chat/tool-execution.loop.ts'],
        "tests": 'Integration: tool invoke metadata',
    },
    {
        "id": 'M7-CHT006',
        "folder": 'm07-ai-chat',
        "title": 'POST /conversations + /messages (non-stream)',
        "milestone": 'M7 — AI Chat',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Create session, send message, persist user/assistant messages.',
        "deps": ['M7-CHT005', 'M3-AUTH008'],
        "traces": 'FR-CHAT-001, FR-CHAT-002',
        "acceptance": ['201 on new conversation', 'Assistant message stored with citations stub'],
        "files": ['backend/src/presentation/ai/conversations.controller.ts', 'backend/src/application/chat/send-message.use-case.ts'],
        "tests": 'Integration: send message happy path',
    },
    {
        "id": 'M7-CHT007',
        "folder": 'm07-ai-chat',
        "title": 'SSE Streaming Endpoint',
        "milestone": 'M7 — AI Chat',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'POST .../messages/stream with token chunks and done event.',
        "deps": ['M7-CHT006'],
        "traces": 'FR-CHAT streaming, gemini integration §3',
        "acceptance": ['Stream completes with done event', 'Client disconnect cancels upstream'],
        "files": ['backend/src/presentation/ai/chat-stream.controller.ts'],
        "tests": 'Integration: SSE event sequence',
    },
    {
        "id": 'M7-CHT008',
        "folder": 'm07-ai-chat',
        "title": 'Conversation Memory Compaction Job',
        "milestone": 'M7 — AI Chat',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Summarize history when token budget exceeded.',
        "deps": ['M7-CHT006'],
        "traces": '`architecture/gemini_integration_layer.md` §4',
        "acceptance": ['Compaction preserves last N turns', 'Job runs via BullMQ'],
        "files": ['backend/src/infrastructure/queue/chat-compaction.processor.ts'],
        "tests": 'Unit: compaction threshold',
    },
    {
        "id": 'M7-CHT009',
        "folder": 'm07-ai-chat',
        "title": 'Mobile Chat UI + Stream Rendering',
        "milestone": 'M7 — AI Chat',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Message list, composer, SSE client, loading states.',
        "deps": ['M3-AUTH011', 'M7-CHT007'],
        "traces": 'AC-CHAT-001, AC-CHAT-002',
        "acceptance": ['Stream renders incrementally', 'AI disclaimer on every assistant bubble'],
        "files": ['mobile/lib/features/ai_chat/**'],
        "tests": 'Widget tests; manual stream on dev API',
    },
    {
        "id": 'M7-CHT010',
        "folder": 'm07-ai-chat',
        "title": 'Mobile Agent Picker + Listing Cards',
        "milestone": 'M7 — AI Chat',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Switch agent mid-session; tap card opens M4 detail.',
        "deps": ['M7-CHT009', 'M4-SEA011', 'M5-PRO005'],
        "traces": 'FR-CHAT-005, FR-CHAT-012',
        "acceptance": ['Agent switch preserves history', 'Listing card navigates to detail'],
        "files": ['mobile/lib/features/ai_chat/presentation/widgets/**'],
        "tests": 'Widget: agent switch; manual card tap',
    },
    {
        "id": 'M7-CHT011',
        "folder": 'm07-ai-chat',
        "title": 'AI Chat P0 Test Pack',
        "milestone": 'M7 — AI Chat',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Integration tests for chat AC including fair housing.',
        "deps": ['M7-CHT007', 'M7-CHT004'],
        "traces": '`features/ai_chat/tests.md`',
        "acceptance": ['All P0 chat AC covered', 'Fair housing test passes'],
        "files": ['backend/test/integration/ai/**'],
        "tests": 'CI: ai chat integration green',
    },
    {
        "id": 'M8-REC001',
        "folder": 'm08-recommendations',
        "title": 'Recommendation Domain + Scoring Port',
        "milestone": 'M8 — Recommendations',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'RecommendationCandidate, Feedback VO, scoring port.',
        "deps": ['M1-REC-REQ', 'M6-RAG003'],
        "traces": '`features/recommendation/data_model.md`',
        "acceptance": ['Domain tests pass', 'No discriminatory attribute filters'],
        "files": ['backend/src/domain/recommendation/**', 'backend/test/unit/domain/recommendation/**'],
        "tests": 'Unit: fair housing filter test',
    },
    {
        "id": 'M8-REC002',
        "folder": 'm08-recommendations',
        "title": 'User Preference Vector Builder',
        "milestone": 'M8 — Recommendations',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Mean embedding of liked listings + preference weights.',
        "deps": ['M8-REC001', 'M5-PRO003'],
        "traces": 'FR-REC-003',
        "acceptance": ['Vector updates on like', 'Cold start returns popular listings'],
        "files": ['backend/src/application/recommendation/preference-vector.ts'],
        "tests": 'Integration: like → vector change',
    },
    {
        "id": 'M8-REC003',
        "folder": 'm08-recommendations',
        "title": 'GET /api/v1/recommendations',
        "milestone": 'M8 — Recommendations',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Personalized feed with pagination and explain stub.',
        "deps": ['M8-REC002', 'M4-SEA006'],
        "traces": 'FR-REC-001, FR-REC-007',
        "acceptance": ['Authenticated user gets non-empty feed', 'Disliked listings excluded'],
        "files": ['backend/src/modules/recommendations/**'],
        "tests": 'Integration: feed pagination',
    },
    {
        "id": 'M8-REC004',
        "folder": 'm08-recommendations',
        "title": 'POST /recommendations/feedback',
        "milestone": 'M8 — Recommendations',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Like/dislike endpoints updating preference vector.',
        "deps": ['M8-REC003'],
        "traces": 'FR-REC-006',
        "acceptance": ['Idempotent feedback', 'Next page reflects dislike'],
        "files": ['backend/src/application/recommendation/feedback.use-case.ts'],
        "tests": 'Integration: like/dislike flow',
    },
    {
        "id": 'M8-REC005',
        "folder": 'm08-recommendations',
        "title": 'Mobile Home Recommendations Section',
        "milestone": 'M8 — Recommendations',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Horizontal feed on home; like/dislike gestures.',
        "deps": ['M8-REC003', 'M2-PLT001'],
        "traces": 'AC-REC-001',
        "acceptance": ['Cold start shows popular', 'Like refreshes recommendations'],
        "files": ['mobile/lib/features/recommendation/**'],
        "tests": 'Widget + manual home feed',
    },
    {
        "id": 'M8-REC006',
        "folder": 'm08-recommendations',
        "title": 'Recommendation P0 Test Pack',
        "milestone": 'M8 — Recommendations',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Integration + compliance tests per tests.md.',
        "deps": ['M8-REC004'],
        "traces": '`features/recommendation/tests.md`',
        "acceptance": ['All P0 REC AC pass', 'No discriminatory filters test'],
        "files": ['backend/test/integration/recommendations/**'],
        "tests": 'CI green',
    },
    {
        "id": 'M9-BOK001',
        "folder": 'm09-booking',
        "title": 'Booking Domain + Repository',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Booking entity, status machine, repository port.',
        "deps": ['M2-PLT003', 'M1-BOK-REQ'],
        "traces": '`features/booking/data_model.md`',
        "acceptance": ['Status transitions validated in domain', 'Unit tests for quota rules stub'],
        "files": ['backend/src/domain/booking/**', 'backend/test/unit/domain/booking/**'],
        "tests": 'Unit: status machine',
    },
    {
        "id": 'M9-BOK002',
        "folder": 'm09-booking',
        "title": 'POST /api/v1/bookings (buyer request)',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Create viewing request linked to property and agent.',
        "deps": ['M9-BOK001', 'M4-SEA007', 'M3-AUTH008'],
        "traces": 'FR-BOOK-001, FR-BOOK-002',
        "acceptance": ['status requested on create', '404 if property inactive'],
        "files": ['backend/src/application/booking/create-booking.use-case.ts'],
        "tests": 'Integration: buyer creates booking',
    },
    {
        "id": 'M9-BOK003',
        "folder": 'm09-booking',
        "title": 'Agent Confirm / Decline / Cancel APIs',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'PATCH transitions; notifications enqueued.',
        "deps": ['M9-BOK002'],
        "traces": 'FR-BOOK-003, FR-BOOK-011',
        "acceptance": ['Agent confirm sets confirmed', 'Buyer cancel before viewing works'],
        "files": ['backend/src/application/booking/update-booking.use-case.ts'],
        "tests": 'Integration: lifecycle transitions',
    },
    {
        "id": 'M9-BOK004',
        "folder": 'm09-booking',
        "title": 'Double-Booking + Agent Quota Guards',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Prevent overlapping slots; 5 free bookings/month for agents.',
        "deps": ['M9-BOK003'],
        "traces": 'FR-BOOK-009, FR-BOOK-010',
        "acceptance": ['Double-book returns 409', 'Quota exceeded returns 403'],
        "files": ['backend/src/domain/booking/booking-policy.service.ts'],
        "tests": 'Integration: conflict + quota tests',
    },
    {
        "id": 'M9-BOK005',
        "folder": 'm09-booking',
        "title": 'NotificationsModule + BullMQ Processor',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'notification_jobs table; processor dispatches push/email.',
        "deps": ['M2-PLT007', 'M9-BOK003'],
        "traces": 'FR-NOTIF-001',
        "acceptance": ['Job enqueued on booking status change', 'Failed job retries with backoff'],
        "files": ['backend/src/modules/notifications/**'],
        "tests": 'Integration: job processed mock',
    },
    {
        "id": 'M9-BOK006',
        "folder": 'm09-booking',
        "title": 'FCM Push Integration',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Send push to agent on new request; buyer on confirm.',
        "deps": ['M9-BOK005'],
        "traces": 'FR-NOTIF-002',
        "acceptance": ['Push payload includes booking id', 'Invalid token handled gracefully'],
        "files": ['backend/src/infrastructure/notifications/fcm.service.ts'],
        "tests": 'Integration: mock FCM server',
    },
    {
        "id": 'M9-BOK007',
        "folder": 'm09-booking',
        "title": 'Bilingual Email Templates (ar/en)',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'MJML/HTML templates for booking events.',
        "deps": ['M9-BOK005'],
        "traces": 'FR-NOTIF-004',
        "acceptance": ['Snapshot tests for both locales', 'Variables substituted correctly'],
        "files": ['backend/src/infrastructure/notifications/templates/**'],
        "tests": 'Snapshot: template render',
    },
    {
        "id": 'M9-BOK008',
        "folder": 'm09-booking',
        "title": 'Mobile Booking Request from Listing Detail',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Date/time picker, notes, submit to API.',
        "deps": ['M4-SEA011', 'M9-BOK002', 'M3-AUTH011'],
        "traces": 'AC-BOOK-001',
        "acceptance": ['Buyer submits request', 'Validation errors shown inline'],
        "files": ['mobile/lib/features/booking/**'],
        "tests": 'Widget + manual booking request',
    },
    {
        "id": 'M9-BOK009',
        "folder": 'm09-booking',
        "title": 'Mobile Agent Booking Inbox',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'List requests; confirm/decline actions.',
        "deps": ['M9-BOK008', 'M9-BOK003'],
        "traces": 'AC-BOOK-003',
        "acceptance": ['Agent confirm updates status in UI', 'Push opens correct booking (deep link stub)'],
        "files": ['mobile/lib/features/booking/presentation/agent/**'],
        "tests": 'Manual agent flow on two simulators',
    },
    {
        "id": 'M9-BOK010',
        "folder": 'm09-booking',
        "title": 'Booking E2E Lifecycle Test',
        "milestone": 'M9 — Booking & Notifications',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Buyer request → agent confirm → notification asserted.',
        "deps": ['M9-BOK006', 'M9-BOK004'],
        "traces": '`features/booking/tests.md`',
        "acceptance": ['Full P0 booking AC pass', 'Notification job completed'],
        "files": ['backend/test/e2e/booking/**'],
        "tests": 'E2E green in CI',
    },
    {
        "id": 'M10-QLT001',
        "folder": 'm10-quality',
        "title": 'MVP Launch Checklist Document',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'docs',
        "description": 'Create tasks/mvp_launch_checklist.md from master plan M10.',
        "deps": ['M9-BOK010', 'M7-CHT011'],
        "traces": '`tasks/master_execution_plan.md` M10',
        "acceptance": ['Checklist covers P0 FR modules', 'Owners assigned per line item'],
        "files": ['tasks/mvp_launch_checklist.md'],
        "tests": 'PO review sign-off',
    },
    {
        "id": 'M10-QLT002',
        "folder": 'm10-quality',
        "title": 'Flutter integration_test P0 Journey',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'auth → search → chat → booking on dev flavor.',
        "deps": ['M9-BOK009', 'M7-CHT010'],
        "traces": 'M10 E2E requirements',
        "acceptance": ['integration_test passes on CI macOS runner', 'Screenshots on failure'],
        "files": ['mobile/integration_test/**'],
        "tests": '`flutter test integration_test`',
    },
    {
        "id": 'M10-QLT003',
        "folder": 'm10-quality',
        "title": 'API E2E Suite (supertest)',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Chained API test: register → sync → chat → book.',
        "deps": ['M9-BOK010'],
        "traces": 'NFR-MAINT-004',
        "acceptance": ['All public REST P0 paths hit', 'Runs in CI with docker services'],
        "files": ['backend/test/e2e/full-journey/**'],
        "tests": '`npm run test:e2e` green',
    },
    {
        "id": 'M10-QLT004',
        "folder": 'm10-quality',
        "title": 'Domain Coverage Gate ≥80%',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Jest coverage threshold on domain/ and application/.',
        "deps": ['M10-QLT003'],
        "traces": 'NFR-MAINT-003',
        "acceptance": ['CI fails below 80% domain coverage', 'Report uploaded as artifact'],
        "files": ['backend/jest.config.js', '.github/workflows/backend-ci.yml'],
        "tests": 'CI coverage job',
    },
    {
        "id": 'M10-QLT005',
        "folder": 'm10-quality',
        "title": 'Prometheus Metrics + Grafana Dashboards',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'API, RAG, AI dashboards per monitoring_strategy.md.',
        "deps": ['M6-RAG008', 'M7-CHT003'],
        "traces": '`architecture/monitoring_strategy.md`',
        "acceptance": ['Dashboards importable JSON committed', 'Staging soak shows data'],
        "files": ['infra/grafana/**', 'backend/src/infrastructure/observability/**'],
        "tests": 'Manual: Grafana panels populate',
    },
    {
        "id": 'M10-QLT006',
        "folder": 'm10-quality',
        "title": 'Firebase Analytics + Crashlytics',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'Wire events for funnel; crash reports in Firebase.',
        "deps": ['M2-PLT001'],
        "traces": '`architecture/monitoring_strategy.md` §3',
        "acceptance": ['Key events fire on auth/search/chat/book', 'Crashlytics symbolication configured'],
        "files": ['mobile/lib/core/analytics/**', 'mobile/ios/Runner/GoogleService-Info.plist'],
        "tests": 'Manual: Firebase debug view',
    },
    {
        "id": 'M10-QLT007',
        "folder": 'm10-quality',
        "title": 'AI Quality Metrics (hallucination, citations)',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'Log invalid listing IDs; weekly hallucination rate query.',
        "deps": ['M7-CHT011'],
        "traces": 'monitoring_strategy AI §',
        "acceptance": ['Metric exported', 'Alert when rate > 3% over 7d'],
        "files": ['backend/src/infrastructure/observability/ai-quality/**'],
        "tests": 'Integration: strip invalid listing id',
    },
    {
        "id": 'M10-QLT008',
        "folder": 'm10-quality',
        "title": 'Security Review Checklist (OWASP + PDPL)',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'docs',
        "description": 'Complete security checklist; fix P0 findings.',
        "deps": ['M3-AUTH012'],
        "traces": 'NFR-SEC-*',
        "acceptance": ['No secrets in repo scan clean', 'JWT/OAuth/PDPL items checked'],
        "files": ['docs/security_review_checklist.md'],
        "tests": 'Security sign-off recorded',
    },
    {
        "id": 'M10-QLT009',
        "folder": 'm10-quality',
        "title": 'Load Test Report (search + chat)',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'k6 or Artillery scripts; p95 targets documented.',
        "deps": ['M4-SEA012', 'M7-CHT007'],
        "traces": 'NFR-PERF-002, NFR-PERF chat',
        "acceptance": ['Search p95 < 2s at 10k listings', 'Chat p95 < 3s at target RPS'],
        "files": ['infra/loadtests/**'],
        "tests": 'Report committed with results',
    },
    {
        "id": 'M10-QLT010',
        "folder": 'm10-quality',
        "title": 'PO MVP Sign-Off Artifact',
        "milestone": 'M10 — Quality, Security & E2E',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'docs',
        "description": 'Sign-off against specs/vision.md success metrics.',
        "deps": ['M10-QLT001', 'M10-QLT009'],
        "traces": '`specs/vision.md`',
        "acceptance": ['Written PO acceptance', 'P0 defects = 0'],
        "files": ['tasks/mvp_signoff.md'],
        "tests": 'PO signature in doc',
    },
    {
        "id": 'M11-DEP001',
        "folder": 'm11-staging-gcp',
        "title": 'GCP Staging Project + WIF for GitHub',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'Create re-agent-staging; workload identity federation.',
        "deps": ['M10-QLT010'],
        "traces": '`architecture/deployment_architecture.md` §4',
        "acceptance": ['GitHub Actions can authenticate without keys', 'Least-privilege SA roles documented'],
        "files": ['infra/terraform/staging/**', '.github/workflows/deploy-staging.yml'],
        "tests": 'gh workflow dry-run auth',
    },
    {
        "id": 'M11-DEP002',
        "folder": 'm11-staging-gcp',
        "title": 'Cloud SQL PostgreSQL + pgvector',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'Private IP Cloud SQL; run Prisma migrate on deploy.',
        "deps": ['M11-DEP001', 'M2-PLT003'],
        "traces": 'deployment_architecture §5',
        "acceptance": ['Migrations apply via CD job', 'vector extension enabled'],
        "files": ['infra/terraform/staging/cloudsql.tf'],
        "tests": 'CD migrate job success',
    },
    {
        "id": 'M11-DEP003',
        "folder": 'm11-staging-gcp',
        "title": 'Cloud Run API + Worker Services',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'Deploy api-staging and worker-staging from Artifact Registry.',
        "deps": ['M11-DEP002', 'M2-PLT004'],
        "traces": 'deployment_architecture §6',
        "acceptance": ['/health/ready returns 200', 'Worker processes listing-sync queue'],
        "files": ['infra/terraform/staging/cloudrun.tf', 'backend/Dockerfile'],
        "tests": 'Post-deploy smoke curl',
    },
    {
        "id": 'M11-DEP004',
        "folder": 'm11-staging-gcp',
        "title": 'Secret Manager Wiring',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'DB URL, Redis, JWT, provider keys in Secret Manager.',
        "deps": ['M11-DEP003'],
        "traces": 'deployment_architecture §7',
        "acceptance": ['No secrets in GitHub vars except WIF', 'Cloud Run mounts secrets'],
        "files": ['infra/terraform/staging/secrets.tf'],
        "tests": 'API boots with secrets only from SM',
    },
    {
        "id": 'M11-DEP005',
        "folder": 'm11-staging-gcp',
        "title": 'Vertex AI Gemini Staging Config',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'backend',
        "description": 'GEMINI_PROVIDER=vertex; service account IAM.',
        "deps": ['M11-DEP004', 'M7-CHT003'],
        "traces": '`architecture/ai_provider_strategy.md`',
        "acceptance": ['Chat stream completes on staging', 'No API key in mobile client'],
        "files": ['backend/src/infrastructure/ai/vertex.config.ts'],
        "tests": 'Staging integration: one chat message',
    },
    {
        "id": 'M11-DEP006',
        "folder": 'm11-staging-gcp',
        "title": 'GitHub Actions deploy-staging Workflow',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'ci',
        "description": 'On main: build, migrate, deploy Cloud Run.',
        "deps": ['M11-DEP003'],
        "traces": 'deployment_architecture §6.2',
        "acceptance": ['Workflow runs on merge to main', 'Failed deploy blocks without rollback doc'],
        "files": ['.github/workflows/deploy-staging.yml'],
        "tests": 'Merge PR → staging updated',
    },
    {
        "id": 'M11-DEP007',
        "folder": 'm11-staging-gcp',
        "title": 'Flutter Staging → Staging API URL',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'staging flavor baseUrl; Firebase App Distribution.',
        "deps": ['M11-DEP003', 'M2-PLT001'],
        "traces": 'deployment_architecture §8',
        "acceptance": ['Staging APK/IPA hits staging API', 'App Distribution testers can install'],
        "files": ['mobile/lib/core/config/flavor.dart', 'mobile/lib/main_staging.dart'],
        "tests": 'Manual: staging build full journey',
    },
    {
        "id": 'M11-DEP008',
        "folder": 'm11-staging-gcp',
        "title": 'Cloud Monitoring Alerts',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'Critical alerts: 5xx rate, DB CPU, AI cost daily.',
        "deps": ['M10-QLT005', 'M11-DEP003'],
        "traces": 'monitoring_strategy §5',
        "acceptance": ['Alert policies deployed', 'Test notification received'],
        "files": ['infra/terraform/staging/alerts.tf'],
        "tests": 'Dry-run alert firing',
    },
    {
        "id": 'M11-DEP009',
        "folder": 'm11-staging-gcp',
        "title": 'Staging Smoke + Rollback Drill',
        "milestone": 'M11 — Staging on GCP',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'ops',
        "description": 'Document and execute rollback to previous Cloud Run revision.',
        "deps": ['M11-DEP006', 'M11-DEP007'],
        "traces": 'M11 DoD',
        "acceptance": ['QA sign-off on staging build', 'Rollback < 5 minutes documented'],
        "files": ['docs/runbooks/staging_rollback.md'],
        "tests": 'Ops drill log attached',
    },
    {
        "id": 'M12-PRD001',
        "folder": 'm12-production',
        "title": 'GCP Production Project + IAM',
        "milestone": 'M12 — Production Release',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 're-agent-prod project; separate SA and VPC.',
        "deps": ['M11-DEP009'],
        "traces": 'deployment_architecture §9',
        "acceptance": ['Prod isolated from staging', 'IAM least privilege documented'],
        "files": ['infra/terraform/production/**'],
        "tests": 'Terraform plan review',
    },
    {
        "id": 'M12-PRD002',
        "folder": 'm12-production',
        "title": 'Production CD (canary + traffic shift)',
        "milestone": 'M12 — Production Release',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'ci',
        "description": 'Tag backend/v* deploy with canary revision.',
        "deps": ['M12-PRD001', 'M11-DEP006'],
        "traces": 'deployment_architecture §6.3',
        "acceptance": ['Canary 10% → 100% promotion', 'Automated rollback on health fail'],
        "files": ['.github/workflows/deploy-production.yml'],
        "tests": 'Tag deploy dry-run on staging first',
    },
    {
        "id": 'M12-PRD003',
        "folder": 'm12-production',
        "title": 'Custom Domain + Managed SSL',
        "milestone": 'M12 — Production Release',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'api.propertyassistant.eg mapped to Cloud Run.',
        "deps": ['M12-PRD002'],
        "traces": 'M12 deliverables',
        "acceptance": ['HTTPS only', 'Certificate provisioned'],
        "files": ['infra/terraform/production/domain.tf'],
        "tests": 'curl https://api.../health',
    },
    {
        "id": 'M12-PRD004',
        "folder": 'm12-production',
        "title": 'Fastlane App Store + Play Release',
        "milestone": 'M12 — Production Release',
        "estimate": '4h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'mobile',
        "description": 'mobile/v* tag triggers store upload (phased rollout).',
        "deps": ['M11-DEP007', 'M10-QLT002'],
        "traces": 'deployment_architecture §8.3',
        "acceptance": ['Fastlane lanes run on CI macOS', 'Phased rollout 10% documented'],
        "files": ['mobile/fastlane/**', '.github/workflows/release-mobile.yml'],
        "tests": 'TestFlight / internal track upload',
    },
    {
        "id": 'M12-PRD005',
        "folder": 'm12-production',
        "title": 'Production Vertex Quotas + Budget Alerts',
        "milestone": 'M12 — Production Release',
        "estimate": '2h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'infra',
        "description": 'Billing budget and Vertex quota limits.',
        "deps": ['M12-PRD001'],
        "traces": 'ai_provider_strategy cost §',
        "acceptance": ['Budget alert at 80% threshold', 'Quota documented in runbook'],
        "files": ['infra/terraform/production/billing.tf'],
        "tests": 'GCP console budget verified',
    },
    {
        "id": 'M12-PRD006',
        "folder": 'm12-production',
        "title": 'Incident Runbook + On-Call Rotation',
        "milestone": 'M12 — Production Release',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'ops',
        "description": 'Pager/on-call schedule; incident severity matrix.',
        "deps": ['M11-DEP009'],
        "traces": 'M12 DoD',
        "acceptance": ['Runbook covers API/AI/DB failures', 'On-call rotation staffed'],
        "files": ['docs/runbooks/incident_response.md'],
        "tests": 'Tabletop exercise completed',
    },
    {
        "id": 'M12-PRD007',
        "folder": 'm12-production',
        "title": 'Production Smoke + Hypercare Dashboard',
        "milestone": 'M12 — Production Release',
        "estimate": '3h',
        "priority": 'P0',
        "status": 'pending',
        "layer": 'ops',
        "description": 'Post-release smoke on real devices; 24h dashboard.',
        "deps": ['M12-PRD003', 'M12-PRD004'],
        "traces": 'M12 verification',
        "acceptance": ['3 device smoke tests pass', 'Week-1 metrics baseline documented'],
        "files": ['tasks/production_launch_report.md'],
        "tests": 'PO hypercare sign-off',
    },
]
